paths:
  save_dir: ../saved_models
  saved_model_path: ../saved_models/d3_d_t_3_240125-111113_load_f_d3_d_t_3_240124-141433_load_f_d3_d_t_3_240123-230657.pt
model_settings:
  hidden_channels_GCN: 
    - 32
    - 64
  hidden_channels_MLP: 
    - 64
    - 32
graph_settings:
  code_size: 3
  repetitions: 3
  min_error_rate: 0.001
  max_error_rate: 0.005
  m_nearest_nodes: 5
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 10000000
  validation_set_size: 50000
  batch_size: 24000
  epochs: 3500
  lr: 0.000001
  device: cuda
  resume_training: True
  current_epoch: 2500

