paths:
  save_dir: ../saved_models
  saved_model_path: ../saved_models/model_231213-170259.pt
graph_settings:
  code_size: 7
  repetitions: 11
  min_error_rate: 0.001
  max_error_rate: 0.005
  m_nearest_nodes: 5
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 1000
  validation_set_size: 2000
  batch_size: 100
  epochs: 10
  lr: 0.001
  device: cuda
  resume_training: False
  current_epoch: 0

